name: Feature Request
description: Propose an improvement for RootSigil
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: As a user, I need ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the change you want
      placeholder: Add/modify ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you considered
  - type: textarea
    id: impact
    attributes:
      label: Security / API Impact
      description: Any implications for security, policy semantics, or OpenAPI
      placeholder: Affects /v1/... and policy rule ...
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submit Checklist
      options:
        - label: I searched existing issues for duplicates.
          required: true
